openapi: 3.2.0
info:
  title: Cvent REST Users API
  description: '# Introduction

    The Cvent API Platform is built around REST.'
  contact:
    name: Cvent Development Platform
    url: https://developers.cvent.com/
  version: ea
servers:
- url: https://api-platform.cvent.com/ea
- url: https://api-platform-eur.cvent.com/ea
tags:
- name: Users
  description: Operations for managing account users and user groups, including creation, retrieval, update, and deletion. Use these endpoints to administer user access and roles within your account.
paths:
  /account-user-groups:
    get:
      summary: List Account User Groups
      description: Gets a list of user groups in your account.
      operationId: getAccountUserGroups
      tags:
      - Users
      security:
      - OAuth2.authorizationCode:
        - account/user-groups:read
      - OAuth2.clientCredentials:
        - account/user-groups:read
    post:
      summary: Create Account User Group
      operationId: createAccountUserGroup
      description: Creates a new Account User Group.
      tags:
      - Users
      security:
      - OAuth2.authorizationCode:
        - account/user-groups:write
      - OAuth2.clientCredentials:
        - account/user-groups:write
  /account-user-groups/{userGroupId}:
    get:
      summary: Get Account User Group
      description: Gets a single account user group by its ID.
      operationId: getAccountUserGroup
      tags:
      - Users
      security:
      - OAuth2.authorizationCode:
        - account/user-groups:read
      - OAuth2.clientCredentials:
        - account/user-groups:read
    put:
      summary: Update Account User Group
      description: Update a given account user group using details in the body of the request.
      operationId: updateAccountUserGroup
      tags:
      - Users
      security:
      - OAuth2.authorizationCode:
        - account/user-groups:write
      - OAuth2.clientCredentials:
        - account/user-groups:write
    delete:
      summary: Delete Account User Group
      description: Deletes an account user group using its ID.
      operationId: deleteAccountUserGroup
      tags:
      - Users
      security:
      - OAuth2.authorizationCode:
        - account/user-groups:delete
      - OAuth2.clientCredentials:
        - account/user-groups:delete
  /account-user-groups/{userGroupId}/users/{userId}:
    post:
      summary: Associate User to Group
      description: Associates a user to an account user group.
      operationId: addUserToAccountUserGroup
      tags:
      - Users
      security:
      - OAuth2.authorizationCode:
        - account/user-groups:write
      - OAuth2.clientCredentials:
        - account/user-groups:write
    delete:
      summary: Delete User from Group
      description: Removes a user from an account user group.
      operationId: deleteUserFromAccountUserGroup
      tags:
      - Users
      security:
      - OAuth2.authorizationCode:
        - account/user-groups:delete
      - OAuth2.clientCredentials:
        - account/user-groups:delete
components:
  securitySchemes:
    OAuth2.authorizationCode:
      type: oauth2
      description: OAuth2 Authorization Code Flow.
      flows:
        authorizationCode:
          authorizationUrl: https://api-platform.cvent.com/ea/oauth2/authorize
          tokenUrl: https://api-platform.cvent.com/ea/oauth2/token
          scopes:
            account/hooks:delete: Allows the deletion of hooks.
            account/hooks:read: Allows the reading of hooks.
            account/hooks:write: Allows the creation/updation of hooks.
            account/user-groups:delete: Allows deletion for user groups
            account/user-groups:read: Allows the reading of user groups
            account/user-groups:write: Allows the writing of user groups
            account/users:delete: Allows the deletion of User
            account/users:read: Allows the reading of User, User Group
            account/users:write: Allows the creation/updating of User
            appointments/appointment-attendees:read: Allows the reading of appointment attendees and their related entities.
            appointments/appointment-events:read: Allows the reading of appointment events and their related entities.
            appointments/appointment-types:read: Allows the reading of appointment types and their related entities.
            appointments/appointments:read: Allows the reading of appointment and their related entities.
            appointments/appointments:write: Allows the writing of appointments and their related entities.
            appointments/available-times:read: Allows the reading of available times.
            appointments/locations:read: Allows the reading of appointment locations and their related entities.
            attendee-insights/attendee-insights:read: Allows the reading of engagement scores (attendee insights).
            attendee-insights/scores:read: Allows the reading of scores.
            attendee-insights/stats:read: Allows the reading of engagement score (attendee insight) stats.
            budget/budget-items:delete: Allows the deletion of budget items
            budget/budget-items:read: Allows the reading of all budget items
            budget/budget-items:write: Allows creation/updation of budget item
            budget/budget-totals:read: Allows the reading of all event budget totals
            budget/budget-vendors:read: Allows reading of account-level budget vendors.
            budget/cards:read: Allows the reading of cards
            budget/currency-conversion-rate:delete: Allows deletion of currency conversion rate for currency.
            budget/currency-conversion-rate:read: Allows reading of currency conversion rate for currency.
            budget/currency-conversion-rate:write: Allows creation/update of currency conversion rate for currency.
            budget/payments:delete: Allows deletion of payments.
            budget/payments:read: Allows reading of payment for budget item.
            budget/payments:write: Allows creation of payment in a budget item.
            budget/transactions:delete: Allows delete card transactions.
            budget/transactions:read: Allows the reading of all card's transactions
            budget/transactions:write: Allows creation of card transactions.
            business-transient/bids:read: Allows the reading of BT Bid data
            business-transient/proposals:read: Allows the reading of BT Proposal data
            business-travel/bids:read: Allows the reading of BT Bid data
            business-travel/proposals:read: Allows the reading of BT Proposal data
            compliance/communications:read: Allows the reading of communication compliance
            compliance/communications:write: Allows the writing of communication compliance
            email/bounces:read: Allow the reading of email bounces.
            email/email-status:read: Allows the reading of email statuses.
            email/emails:read: Allows the reading of emails.
            eMarketing/campaigns:read: Allows the reading of campaigns.
            emarketing/emarketing-email-status:read: Allows the reading of eMarketing email statuses.
            eMarketing/eMarketing-email-templates:read: Allows the reading of email-templates.
            eMarketing/eMarketing-send-emails:write: Allows the writing of eMarketing emails.
            event/admission-items:read: Allows the reading of admission items
            event/air-request:read: Allow reading the air request or air actual detail for attendees.
            event/alternate-travel:read: Allow reading the alternate travel answers for attendees.
            event/attendance-durations:read: Allows the read of Duration records
            event/attendee-activities-metadata:delete: Allows the deletion of attendees activities metadata.
            event/attendee-activities-metadata:read: Allows the reading of attendee activities metadata.
            event/attendee-activities-metadata:write: Allows the creation/updating of attendees activities metadata.
            event/attendee-activities:read: Allows the reading of attendee activities.
            event/attendee-activities:write: Allows the writing of attendee activities.
            event/attendee-credits:read: Allows the reading of attendee credits.
            event/attendee-links:delete: Allows the deletion of attendee links
            event/attendee-links:read: Allows the reading of attendee links
            event/attendee-links:write: Allows the creation of attendee links
            event/attendee-messages:read: Allows the reading of attendee messages
            event/attendees:read: Allows the reading of attendees.
            event/attendees:write: Allows the creation of an attendee in an event.
            event/audience-segments:read: Allows the reading of audience segments.
            event/audience-segments:write: Allows the creation/updating/deletion of audience segments.
            event/contact-groups:read: Allows the reading of contact groups.
            event/contact-groups:write: Allows the creation/updating of contact groups.
            event/contact-types:read: Allows the reading of contact types.
            event/contacts:delete: Allows the deletion of contacts.
            event/contacts:read: Allows the reading of contacts.
            event/contacts:write: Allows the creation/updating of contacts.
            event/contacts:write-sensitive: Allows the creation/updating of sensitive data related to contacts.
            event/custom-fields:read: Allows the reading of custom fields
            event/custom-fields:write: Allows the writing of custom fields
            event/discounts:write: Allows the writing of discounts
            event/donation-items:read: Allows the reading of donation items.
            event/event-discounts:read: Allows the reading of event discounts.
            event/event-discounts:write: Allows the writing of event discounts.
            event/event-email-status:read: Allows the reading of event email statuses.
            event/event-emails:read: Allows the reading of event emails
            event/event-emails:write: Allows to send event emails.
            event/event-features:read: Allows the reading of events-features
            event/event-features:write: Allows updating the event-features
            event/event-user-groups:read: Allows the reading of user groups
            event/event-user-groups:write: Allows associating/disassociating user groups to event
            event/events:read: Allows the reading of events
            event/events:write: Allows the creation/updating of events
            event/fee-items:read: Allows the reading of fee items.
            event/hotel-request:read: Allow reading the hotel request or housing reservation request detail for attendees.
            event/invitation-lists:read: Allows the reading of the invitation lists for an event
            event/meeting-request-forms:read: Allows the reading of meeting request forms.
            event/meeting-requests:read: Allows the reading of meeting requests.
            event/meeting-requests:write: Allows the creation/updating of meeting requests.
            event/membership-items:read: Allows reading of membership items.
            event/orders:read: Allows the reading of orders
            event/planning-documents:read: Allows the reading of event planning documents
            event/players:read: Allows the reading of players
            event/process-form-submissions:read: Allows the reading of process form submissions.
            event/program-items:delete: Allows deletion of session program items
            event/program-items:read: Allows reading of session program items
            event/program-items:write: Allows writing of session program items
            event/quantity-items:read: Allows the reading of quantity items.
            event/quantity-items:write: Allows the writing of quantity items
            event/registration-paths:read: Allows the reading of registration paths
            event/registration-types:read: Allows the reading of registration types
            event/registration-types:write: Allows the writing of registration types
            event/role-assignments:read: Allows the reading of event role assignment.
            event/session-attendance:read: Allows the reading of sessions attendance
            event/session-attendance:write: Allows the creation/updating of sessions attendance
            event/session-categories:read: Allows reading of session categories
            event/session-categories:write: Allows writing of session categories
            event/session-enrollment:delete: Allows the deletion of session registrations
            event/session-enrollment:read: Allows the reading of sessions registrations
            event/session-enrollment:write: Allows the writing of sessions registrations
            event/session-segments:read: Allows reading of session segments
            event/sessions:delete: Allows the deletion of a session in an event
            event/sessions:read: Allows the reading of sessions
            event/sessions:write: Allows the creation of a session in an event
            event/speaker-categories:read: Allows reading of speaker categories
            event/speaker-categories:write: Allows writing of speaker categories
            event/speakers:delete: Allows the deletion of a speaker in an event
            event/speakers:read: Allows the reading of speakers
            event/speakers:write: Allows the creation of a speaker in an event
            event/taxes:read: Allows the reading of taxes.
            event/transactions:read: Allows the reading of transactions
            event/transactions:write: Allows the writing of transactions
            event/video-views:read: Allows reading of video views.
            event/videos:read: Allows the reading of video data.
            event/videos:write: Allows the creation/updating of video data.
            event/vouchers:read: Allows reading of event vouchers and their associated attendees.
            event/webcasts:delete: Allows the deletion of webcast
            event/webcasts:read: Allows the reading of webcasts
            event/webcasts:write: Allows the creation of webcast
            event/weblinks:read: Allows the reading of event weblinks
            events-plus/hubs:read: Allows the reading of Events+ hub data.
            exhibitor/badges:read: Allows reading badges
            exhibitor/badges:write: Allows creating/updating badges
            exhibitor/booth-staff:delete: Allows deleting booth staff
            exhibitor/booth-staff:read: Allows reading booth staff
            exhibitor/booth-staff:write: Allows creating booth staff
            exhibitor/eliterature-requests:read: Allows reading eliterature document request data
            exhibitor/exhibitor-admins:read: Allows reading exhibitor admins
            exhibitor/exhibitor-admins:write: Allows creating/updating exhibitor admins
            exhibitor/exhibitor-answers:read: Allows reading exhibitor answers
            exhibitor/exhibitor-answers:write: Allows updating exhibitor answers
            exhibitor/exhibitor-categories:delete: Allows deleting exhibitor categories
            exhibitor/exhibitor-categories:read: Allows reading exhibitor categories
            exhibitor/exhibitor-categories:write: Allows creating/updating exhibitor categories
            exhibitor/exhibitor-contents:delete: Allows deleting exhibitor content
            exhibitor/exhibitor-contents:read: Allows reading exhibitor content
            exhibitor/exhibitor-contents:write: Allows creating/updating exhibitor content
            exhibitor/exhibitor-questions:read: Allows reading exhibitor questions
            exhibitor/exhibitors:delete: Allows deleting exhibitors
            exhibitor/exhibitors:read: Allows reading exhibitors
            exhibitor/exhibitors:write: Allows creating/updating exhibitors
            exhibitor/lead-qualification-answers:read: Allows reading Lead Qualification Answers
            exhibitor/lead-qualification-questions:read: Allows reading Lead Qualification Questions.
            exhibitor/leads:read: Allows reading leads.
            exhibitor/registration-packs:delete: Allows deleting registration pack
            exhibitor/registration-packs:read: Allows reading registration pack
            exhibitor/registration-packs:write: Allows creating/updating registration pack
            exhibitor/sponsorship-levels:read: Allows reading sponsorship level
            file/file:read: Allows the reading of file
            file/file:write: Allows the uploading of file
            onsite/signatures:read: Allows reading signatures.
            remote-printing/badge-print-jobs:read: Allows reading print jobs.
            remote-printing/badge-print-jobs:write: Allows creating print jobs.
            remote-printing/badge-printer-pools:read: Allows reading pools.
            rfp/rfp-agenda-items:read: Allows the reading of RFP agenda items.
            rfp/rfp-attachments:read: Allows the reading of RFP attachments.
            rfp/rfp-custom-fields:read: Allows the reading of RFP custom fields.
            rfp/rfp-guest-rooms:read: Allows the reading of RFP guest rooms.
            rfp/rfp-internal-documents:read: Allows the reading of RFP internal documents.
            rfp/rfp-lead-sources:read: Allows the reading of RFP lead sources.
            rfp/rfp-past-events:read: Allows the reading of past events similar to rfp event.
            rfp/rfp-questions:read: Allows the reading of RFP questions.
            rfp/rfp-recipients-history:read: Allows the reading of RFP recipients history.
            rfp/rfp-suppliers:read: Allows the reading of RFP suppliers.
            rfp/rfps:read: Allows the reading of basic details of RFP.
            seating/assignments:read: Allows to read attendee seat assignment information.
            seating/event-seatings:read: Allows to read event seating.
            seating/seats:read: Allows to read seat information.
            seating/tables:read: Allows to read table information.
            survey/questions:read: Allows the reading of survey questions
            survey/respondents:read: Allows reading the survey respondents
            survey/responses:read: Allows reading the survey responses
            survey/standard-survey-email-templates:read: Allows reading the standalone survey email templates
            survey/standard-survey-email:write: Allows writing operations on standalone survey emails
            survey/standard-survey-questions:read: Allows the reading of standalone surveys questions
            survey/standard-survey-respondents:read: Allows reading the standalone survey respondents
            survey/standard-survey-respondents:write: Allows write operations on standalone survey respondents
            survey/standard-survey-responses:read: Allows reading the standalone survey responses
            survey/standard-survey-responses:write: Allows write operations on standalone surveys respondent's responses
            survey/standard-surveys:read: Allows the reading of standalone surveys
            survey/survey-questions:read: Allows the reading of event survey questions
            survey/survey-respondents:read: Allows reading the event survey respondents
            survey/survey-respondents:write: Allows write operations on the event survey respondents
            survey/survey-responses:read: Allows reading the event survey responses
            survey/survey-responses:write: Allows write operations on the event surveys respondent's responses
            survey/surveys:read: Allows the reading of event surveys
            venue/meeting-room-images:delete: Allows disassociating images from meeting rooms.
            venue/meeting-room-images:read: Allows retrieving meeting room images.
            venue/meeting-room-images:write: Allows associating images with meeting rooms.
            venue/meeting-room-overviews:read: Allows read access for overview of meeting room.
            venue/meeting-rooms:write: Allows the creation and modification of meeting rooms.
            venue/venue-details-overview:read: Allows read access for overview of venue details.
            venue/venue-details:write: Allows the creation and modification of venue details.
            venue/venue-facility:write: Allows the modification of venue facility information.
    OAuth2.clientCredentials:
      type: oauth2
      description: OAuth2 Client Credentials Flow.
      flows:
        clientCredentials:
          tokenUrl: https://api-platform.cvent.com/ea/oauth2/token
          scopes:
            account/hooks:delete: Allows the deletion of hooks.
            account/hooks:read: Allows the reading of hooks.
            account/hooks:write: Allows the creation/updation of hooks.
            account/user-groups:delete: Allows deletion for user groups
            account/user-groups:read: Allows the reading of user groups
            account/user-groups:write: Allows the writing of user groups
            account/users:delete: Allows the deletion of User
            account/users:read: Allows the reading of User, User Group
            account/users:write: Allows the creation/updating of User
            appointments/appointment-attendees:read: Allows the reading of appointment attendees and their related entities.
            appointments/appointment-events:read: Allows the reading of appointment events and their related entities.
            appointments/appointment-types:read: Allows the reading of appointment types and their related entities.
            appointments/appointments:read: Allows the reading of appointment and their related entities.
            appointments/appointments:write: Allows the writing of appointments and their related entities.
            appointments/available-times:read: Allows the reading of availability times.
            appointments/locations:read: Allows the reading of appointment locations and their related entities.
            attendee-insights/attendee-insights:read: Allows the reading of engagement scores (attendee insights).
            attendee-insights/scores:read: Allows the reading of scores.
            attendee-insights/stats:read: Allows the reading of engagement score (attendee insight) stats.
            budget/budget-items:delete: Allows the deletion of budget items
            budget/budget-items:read: Allows the reading of all budget items
            budget/budget-items:write: Allows creation/updation of budget item
            budget/budget-totals:read: Allows the reading of all event budget totals
            budget/budget-vendors:read: Allows reading of account-level budget vendors.
            budget/cards:read: Allows the reading of cards
            budget/currency-conversion-rate:delete: Allows deletion of currency conversion rate for currency.
            budget/currency-conversion-rate:read: Allows reading of currency conversion rate for currency.
            budget/currency-conversion-rate:write: Allows creation/update of currency conversion rate for currency.
            budget/payments:delete: Allows deletion of payments.
            budget/payments:read: Allows reading of payment for budget item.
            budget/payments:write: Allows creation of payment in a budget item.
            budget/transactions:delete: Allows delete card transactions.
            budget/transactions:read: Allows the reading of all card's transactions
            budget/transactions:write: Allows creation of card transactions.
            bulk/bulk-jobs:read: Allows the reading of bulk job related entities
            bulk/bulk-jobs:write: Allows the creation, update and deletion of bulk job related entities
            business-transient/bids:read: Allows the reading of Business Transient Bid data
            business-transient/proposals:read: Allows the reading of Business Transient Proposal data
            business-transient/supplier-brands:read: Allows the reading of a supplier brand or a list of travel supplier brands.
            business-transient/supplier-chains:read: Allows the reading of a travel supplier chain or a list of travel supplier chains.
            business-transient/supplier-properties:read: Allows the reading of a travel supplier property or a list of travel supplier properties.
            business-transient/supplier-property-rooms:read: Allows the reading of a list of travel supplier property rooms.
            business-transient/travel-accounts:read: Allows the reading of business transient travel account data.
            business-transient/travel-program-questions:read: Allows the reading of business transient travel program question data.
            business-transient/travel-programs:read: Allows the reading of business transient travel program data.
            business-transient/travel-supplier-accounts:read: Allows the reading of business transient travel supplier account data.
            business-travel/bids:read: Allows the reading of Business Travel Bid data
            business-travel/proposals:read: Allows the reading of Business Travel Proposal data
            business-travel/travel-accounts:read: Allows the reading of business travel account data.
            business-travel/travel-program-questions:read: Allows the reading of business travel program question data.
            business-travel/travel-programs:read: Allows the reading of business travel program data.
            compliance/communications:read: Allows the reading of communication compliance
            compliance/communications:write: Allows the writing of communication compliance
            email/bounces:read: Allow the reading of email bounces.
            email/email-status:read: Allows the reading of email statuses.
            email/emails:read: Allows the reading of emails.
            eMarketing/campaigns:read: Allows the reading of campaigns.
            emarketing/emarketing-email-status:read: Allows the reading of eMarketing email statuses.
            eMarketing/eMarketing-email-templates:read: Allows the reading of email-templates.
            eMarketing/eMarketing-send-emails:write: Allows the writing of eMarketing emails.
            event/admission-items:read: Allows the reading of admission items
            event/air-request:read: Allow reading the air request or air actual detail for attendees.
            event/alternate-travel:read: Allow reading the alternate travel answers for attendees.
            event/attendance-durations:read: Allows the read of Duration records
            event/attendee-activities-metadata:delete: Allows the deletion of attendees activities metadata.
            event/attendee-activities-metadata:read: Allows the reading of attendee activities metadata.
            event/attendee-activities-metadata:write: Allows the creation/updating of attendees activities metadata.
            event/attendee-activities:read: Allows the reading of attendee activities.
            event/attendee-activities:write: Allows the writing of external attendee activities.
            event/attendee-credits:read: Allows the reading of attendee credits.
            event/attendee-links:delete: Allows the deletion of attendee links
            event/attendee-links:read: Allows the reading of attendee links
            event/attendee-links:write: Allows the creation of attendee links
            event/attendee-messages:read: Allows the reading of attendee messages
            event/attendees:read: Allows the reading of attendees.
            event/attendees:write: Allows the creation of an attendee in an event.
            event/audience-segments:read: Allows the reading of audience segments.
            event/audience-segments:write: Allows the creation/updating/deletion of audience segments.
            event/contact-groups:read: Allows the reading of contact groups.
            event/contact-groups:write: Allows the creation/updating of contact groups.
            event/contact-types:read: Allows the reading of contact types.
            event/contacts:delete: Allows the deletion of contacts.
            event/contacts:read: Allows the reading of contacts.
            event/contacts:write: Allows the creation/updating of contacts.
            event/contacts:write-sensitive: Allows the creation/updating of sensitive data related to contacts.
            event/custom-fields:read: Allows the reading of custom fields
            event/custom-fields:write: Allows the writing of custom fields
            event/discounts:write: Allows the writing of discounts
            event/donation-items:read: Allows the reading of donation items.
            event/event-discounts:read: Allows the reading of event discounts.
            event/event-discounts:write: Allows the writing of event discounts.
            event/event-email-status:read: Allows the reading of event email statuses.
            event/event-emails:read: Allows the reading of event emails
            event/event-emails:write: Allows to send event emails.
            event/event-features:read: Allows the reading of events-features
            event/event-features:write: Allows updating the event-features
            event/event-user-groups:read: Allows the reading of user groups
            event/event-user-groups:write: Allows associating/disassociating user groups to event
            event/events:read: Allows the reading of events
            event/events:write: Allows the creation/updating of events
            event/fee-items:read: Allows the reading of fee items.
            event/hotel-request:read: Allow reading the hotel request or housing reservation request detail for attendees.
            event/invitation-lists:read: Allows the reading of the invitation lists for an event
            event/meeting-request-forms:read: Allows the reading of meeting request forms.
            event/meeting-requests:read: Allows the reading of meeting requests.
            event/meeting-requests:write: Allows the creation/updating of meeting requests.
            event/membership-items:read: Allows reading of membership items.
            event/orders:read: Allows the reading of orders
            event/planning-documents:read: Allows the reading of event planning documents
            event/players:read: Allows the reading of players
            event/process-form-submissions:read: Allows the reading of process form submissions.
            event/program-items:delete: Allows deletion of session program items
            event/program-items:read: Allows reading of session program items
            event/program-items:write: Allows writing of session program items
            event/quantity-items:read: Allows the reading of quantity items.
            event/quantity-items:write: Allows the writing of quantity items
            event/registration-paths:read: Allows the reading of registration paths
            event/registration-types:read: Allows the reading of registration types
            event/registration-types:write: Allows the writing of registration types
            event/role-assignments:read: Allows the reading of event role assignment.
            event/session-attendance:read: Allows the reading of sessions attendance
            event/session-attendance:write: Allows the creation/updating of sessions attendance
            event/session-categories:read: Allows reading of session categories
            event/session-categories:write: Allows writing of session categories
            event/session-enrollment:delete: Allows the deletion of session registrations
            event/session-enrollment:read: Allows the reading of sessions registrations
            event/session-enrollment:write: Allows the writing of sessions registrations
            event/session-segments:read: Allows reading of session segments
            event/sessions:delete: Allows the deletion of a session in an event
            event/sessions:read: Allows the reading of sessions
            event/sessions:write: Allows the creation of a session in an event
            event/speaker-categories:read: Allows reading of speaker categories
            event/speaker-categories:write: Allows writing of speaker categories
            event/speakers:delete: Allows the deletion of a speaker in an event
            event/speakers:read: Allows the reading of speakers
            event/speakers:write: Allows the creation of a speaker in an event
            event/taxes:read: Allows the reading of taxes.
            event/transactions:read: Allows the reading of transactions
            event/transactions:write: Allows the writing of transactions
            event/video-views:read: Allows reading of video views.
            event/videos:read: Allows the reading of video data.
            event/videos:write: Allows the creation/updating of video data.
            event/vouchers:read: Allows reading of event vouchers.
            event/webcasts:delete: Allows the deletion of webcast
            event/webcasts:read: Allows the reading of webcasts
            event/webcasts:write: Allows the creation of webcast
            event/weblinks:read: Allows the reading of event weblinks
            events-plus/hubs:read: Allows the reading of Events+ hub data.
            exhibitor/badges:read: Allows reading badges
            exhibitor/badges:write: Allows creating/updating badges
            exhibitor/booth-staff:delete: Allows deleting booth staff
            exhibitor/booth-staff:read: Allows reading booth staff
            exhibitor/booth-staff:write: Allows creating booth staff
            exhibitor/eliterature-requests:read: Allows reading eliterature document request data
            exhibitor/exhibitor-admins:read: Allows reading exhibitor admins
            exhibitor/exhibitor-admins:write: Allows creating/updating exhibitor admins
            exhibitor/exhibitor-answers:read: Allows reading exhibitor answers
            exhibitor/exhibitor-answers:write: Allows updating exhibitor answers
            exhibitor/exhibitor-categories:delete: Allows deleting exhibitor categories
            exhibitor/exhibitor-categories:read: Allows reading exhibitor categories
            exhibitor/exhibitor-categories:write: Allows creating/updating exhibitor categories
            exhibitor/exhibitor-contents:delete: Allows deleting exhibitor content
            exhibitor/exhibitor-contents:read: Allows reading exhibitor content
            exhibitor/exhibitor-contents:write: Allows creating/updating exhibitor content
            exhibitor/exhibitor-questions:read: Allows reading exhibitor questions
            exhibitor/exhibitors:delete: Allows deleting exhibitors
            exhibitor/exhibitors:read: Allows reading exhibitors
            exhibitor/exhibitors:write: Allows creating/updating exhibitors
            exhibitor/lead-qualification-answers:read: Allows reading Lead Qualification Answers
            exhibitor/lead-qualification-questions:read: Allows reading Lead Qualification Questions.
            exhibitor/leads:read: Allows reading leads.
            exhibitor/registration-packs:delete: Allows deleting registration pack
            exhibitor/registration-packs:read: Allows reading registration pack
            exhibitor/registration-packs:write: Allows creating/updating registration pack
            exhibitor/sponsorship-levels:read: Allows reading sponsorship level
            file/file:read: Allows the reading of file
            file/file:write: Allows the uploading of file
            housing/connections:write: Allows the user to connect to the Reglink APIs.
            housing/hotel-room-rates:write: Allows the user to create/update hotel room rates.
            housing/housing-event-available-nights:read: Allows the user to read availability information for given event.
            housing/housing-event-hotels:read: Allows the user to read information about event hotels.
            housing/housing-event-inventory:read: Allows the user to get information about housing event inventory.
            housing/housing-event-room-types:read: Allows the user to read information about event room types.
            housing/housing-events:read: Allows the user to read information about events.
            housing/reservation-requests:delete: Allows the user to cancel reservation request.
            housing/reservation-requests:read: Allows the user to read reservation request information.
            housing/reservation-requests:write: Allows the user to create/update reservation request.
            housing/reservations-link:delete: Allows the user to remove association from reservation.
            housing/reservations-link:write: Allows the user to associate reservation to reservation request.
            housing/reservations:delete: Allows the user to cancel reservation.
            housing/reservations:read: Allows the user to read reservation details information.
            housing/reservations:write: Allows the user to create/update reservation.
            onsite/signatures:read: Allows reading signatures.
            proposal/proposals:write: Allows the creation/writing of proposal
            remote-printing/badge-print-jobs:read: Allows reading print jobs.
            remote-printing/badge-print-jobs:write: Allows creating print jobs.
            remote-printing/badge-printer-pools:read: Allows reading pools.
            rfp/rfp-agenda-items:read: Allows the reading of RFP agenda items.
            rfp/rfp-attachments:read: Allows the reading of RFP attachments.
            rfp/rfp-custom-fields:read: Allows the reading of RFP custom fields.
            rfp/rfp-guest-rooms:read: Allows the reading of RFP guest rooms.
            rfp/rfp-internal-documents:read: Allows the reading of RFP internal documents.
            rfp/rfp-lead-sources:read: Allows the reading of RFP lead sources.
            rfp/rfp-past-events:read: Allows the reading of past events similar to rfp event.
            rfp/rfp-questions:read: Allows the reading of RFP questions.
            rfp/rfp-recipients-history:read: Allows the reading of RFP recipients history.
            rfp/rfp-suppliers:read: Allows the reading of RFP suppliers.
            rfp/rfps:read: Allows the reading of basic details of RFP.
            seating/assignments:read: Allows to read attendee seat assignment information.
            seating/event-seatings:read: Allows to read event seating.
            seating/seats:read: Allows to read seat information.
            seating/tables:read: Allows to read table information.
            secure-ecommerce/card-tokens:write: Allows creation of credit card tokens
            survey/questions:read: Allows the reading of survey questions
            survey/respondents:read: Allows reading the survey respondents
            survey/responses:read: Allows reading the survey responses
            survey/standard-survey-email-templates:read: Allows reading the standalone survey email templates
            survey/standard-survey-email:write: Allows writing operations on standalone survey emails
            survey/standard-survey-questions:read: Allows the reading of standalone surveys questions
            survey/standard-survey-respondents:read: Allows reading the standalone survey respondents
            survey/standard-survey-respondents:write: Allows write operations on standalone survey respondents
            survey/standard-survey-responses:read: Allows reading the standalone survey responses
            survey/standard-survey-responses:write: Allows write operations on standalone surveys respondent's responses
            survey/standard-surveys:read: Allows the reading of standalone surveys
            survey/survey-questions:read: Allows the reading of event survey questions
            survey/survey-respondents:read: Allows reading the event survey respondents
            survey/survey-respondents:write: Allows write operations on the event survey respondents
            survey/survey-responses:read: Allows reading the event survey responses
            survey/survey-responses:write: Allows write operations on the event surveys respondent's responses
            survey/surveys:read: Allows the reading of event surveys
            venue/meeting-room-images:delete: Allows disassociating images from meeting rooms.
            venue/meeting-room-images:read: Allows retrieving meeting room images.
            venue/meeting-room-images:write: Allows associating images with meeting rooms.
            venue/meeting-room-overviews:read: Allows read access for overview of meeting room.
            venue/meeting-rooms:write: Allows the creation and modification of meeting rooms.
            venue/venue-details-overview:read: Allows read access for overview of venue details.
            venue/venue-details:write: Allows the creation and modification of venue details.
            venue/venue-facility:write: Allows the modification of venue facility information.
    CallbackApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: This security scheme is used to indicate that Cvent should use API Key auth when invoking your callback. This scheme is only supported for callback operations, and cannot be used to make calls to Cvent endpoints.
    CallbackBasicAuth:
      type: http
      scheme: basic
      description: This security scheme is used to indicate that Cvent should use basic auth when invoking your callback. This scheme is only supported for callback operations, and cannot be used to make calls to Cvent endpoints.